# Generated by Django 3.2.6 on 2021-08-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20210812_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
